[package]
name = "lich"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phylactery = { git = "https://github.com/nyanzoo/phylactery" }
