version: 3

tasks:
  put:
    cmds:
      - cargo run --release -- -H 127.0.0.1 -p 666 put-only --key-set cat --value-size 128 --count 1000000

  put_and_get:
    cmds:
      - cargo run --release -- -H 127.0.0.1 -p 666 put-and-get --key-set cat --value-size 128 --count 1000000 --distribution 0.5
