apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /opt/lich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  storageClassName: ""
  volumeName: backend
  accessModes:
    - ReadWriteOnce
  storageClassName: standard 
  resources:
    requests:
      storage: 1Gi
