apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/lich
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "app"
          operator: In
          values:
            - backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  storageClassName: local-path
  volumeName: backend-pv
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 100Mi
