apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: operator
  serviceName: operator
  replicas: 1
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          env:
            - name: RUST_LOG
              value: {{ .Values.operator.logLevel }}
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: operator-config
              mountPath: /etc/lich
              readOnly: true
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
          ports:
            - containerPort: 666
      volumes:
        - name: operator-config
          configMap:
            name: operator-config
