apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  clusterIP: None
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 666
      targetPort: 666
  internalTrafficPolicy: Cluster
