apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6666
      nodePort: 30001
      targetPort: 6666
  selector:
    app: frontend
