apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 6666
  selector:
    app: frontend
