apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - protocol: TCP
      port: 666
      targetPort: 666
      # comment out if not using NodePort
      nodePort: 30666
  selector:
    app: frontend
