apiVersion: v1
kind: Service
metadata:
  name: operator
spec:
  clusterIP: None
  selector:
    app: operator
  ports:
    - name: operator
      protocol: TCP
      port: 666
      targetPort: 666
  internalTrafficPolicy: Cluster
