backend:
  image: backend
  imagePullPolicy: IfNotPresent
  replicas: 3
  logLevel: info
  config: |
    [endpoints]
    port=666
    operator_addr='operator-0.operator.default.svc.cluster.local:666'

    [store]
    path = '/opt/lich/store'
    version = 'V1'

    [store.meta]
    max_disk_usage = 4096
    max_key_size = 128

    [store.data]
    node_size = 4096

    [incoming_pool]
    block_size = 4096
    capacity = 1024

    [outgoing_pool]
    block_size = 4096
    capacity = 1024
frontend:
  image: frontend
  imagePullPolicy: IfNotPresent
  replicas: 3
  logLevel: info
  config: |
    [endpoints]
    port=666
    operator_addr='operator-0.operator.default.svc.cluster.local:666'

    [incoming_pool]
    block_size = 4096
    capacity = 1024

    [outgoing_pool]
    block_size = 4096
    capacity = 1024
operator:
  image: operator
  imagePullPolicy: IfNotPresent
  logLevel: debug
  config: |
    port=666
