backend:
  image: backend
  replicas: 3
  logLevel: info
  store: |
    [endpoints]
    port=666

    [[stores]]
    dir = '/opt/lich/store1'
    shards = 100
    data_len = 4096
    meta_len = 1048576
    max_disk_usage = 268435456
    block_size = 4096
    capacity = 4096

    [[stores]]
    dir = '/opt/lich/store2'
    shards = 100
    data_len = 4096
    meta_len = 1048576
    max_disk_usage = 268435456
    block_size = 4096
    capacity = 4096

    [[stores]]
    dir = '/opt/lich/store3'
    shards = 100
    data_len = 4096
    meta_len = 1048576
    max_disk_usage = 268435456
    block_size = 4096
    capacity = 4096

    [[stores]]
    dir = '/opt/lich/store4'
    shards = 100
    data_len = 4096
    meta_len = 1048576
    max_disk_usage = 268435456
    block_size = 4096
    capacity = 4096

    [incoming_pool]
    block_size = 4096
    capacity = 4096

    [outgoing_pool]
    block_size = 4096
    capacity = 4096
frontend:
  image: frontend
  imagePullPolicy: IfNotPresent
  replicas: 1
  logLevel: info
  config: |
    [endpoints]
    port=666
    operator_addr='operator-0.operator.default.svc.cluster.local:666'

    [incoming_pool]
    block_size = 4096
    capacity = 4096

    [outgoing_pool]
    block_size = 4096
    capacity = 4096
operator:
  image: operator
