backend:
  image: backend
  replicas: 3
  store: |
    [endpoints]
    port=6666

    [store]
    path = '/opt/lich/store'
    meta_size = 1024
    node_size = 1048576
    version = 1
frontend:
  image: frontend
  replicas: 3
operator:
  image: operator
