version: 3

tasks:
  build-debug:
    cmds:
      - cargo build

  build-release:
    cmds:
      - cargo build --release

  build-image:
    cmds:
      - docker build -f Dockerfile -t operator ..

  clippy:
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  tag-image:
    internal: true
    cmds:
      - docker tag operator {{.REGISTRY}}/operator:{{.VERSION}}

  push-image:
    internal: true
    cmds:
      - docker push {{.REGISTRY}}/operator:{{.VERSION}}

  test:
    cmds:
      - cargo test --all-targets --all-features
